#!/usr/bin/env python
# -*- coding: utf-8 -*-

# -*- coding: utf-8 -*-

import unittest
from test_mathfunc import TestMathFunc
from HTMLTestRunner import HTMLTestRunner
# from HTMLTestReportYIF import HTMLTestRunner

if __name__ == '__main__':
    suite = unittest.TestSuite()

    # tests = [TestMathFunc("test_add"), TestMathFunc("test_minus"), TestMathFunc("test_multi"), TestMathFunc("test_divide")]
    # suite.addTests(tests)
    # runner = unittest.TextTestRunner(verbosity=2)
    # runner.run(suite)

    '''
    suite.addTests(unittest.TestLoader().loadTestsFromName("test_multi",TestMathFunc))
    loadTestsFromNames(self, names, module=None) --和上面功能相同，只不过接受的是字符串列表
    loadTestsFromTestCase(self, testCaseClass)--根据给定的测试类，获取其中的所有测试方法，并返回一个测试套件
    '''
    # 将结果输出到文件
    # suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))
    # 在同目录创建文件
    # with open('UnittestTextReport.txt', 'a') as f:
    #         runner = unittest.TextTestRunner(stream=f, verbosity=2)
    #         runner.run(suite)


    # 将结果以WEB的形式输出,需要from HTMLTestRunner import HTMLTestRunner
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))
    with open('HTMLReport.html', 'wb+') as f:
        runner = HTMLTestRunner(stream=f,
                                title='MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)


    # suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))
    # with open('HTMLReportYIF.html', 'wb+') as f:
    #     runner = HTMLTestRunner(stream=f,
    #                             title='MathFunc Test Report',
    #                             description='generated by HTMLTestRunner.'
    #                             )
    #     runner.run(suite)

